### ISSUE TITLE
make install doesn't copy femto.boot and is this file is expected in bin

### ISSUE THREAD

**Issue by sleep-walker** [FemtoEmacs/Femto-Emacs#6]
I'm preparing Femto-Emacs package for openSUSE (currently lives [here](https://build.opensuse.org/package/show/editors/Femto-Emacs) because I don't know much tiny emacs-like editors which are functional...

I found 2 problems:
1] `make install` doesn't copy `femto.boot`
2] `femto.boot` is expected in the same path as `femto` (in my case /usr/bin)

For now I installed `femto` and `femto.boot` manually and patched the code to find the file in the location I defined. It would be nice if it would be configurable.

**Comment by domus123** [comment]
Will fix make install script, but for now, you can run **install.sh script**

**Comment by domus123** [comment]
Now we have a "make install" working. Thank you for bringing the problem to us !
