### ISSUE TITLE
Use of isspace (3) in a loop.

### ISSUE THREAD

**Issue by chigoncalves** [FemtoEmacs/Femto-Emacs#7]
In these lines: [52](https://github.com/FemtoEmacs/Femto-Emacs/blob/master/utils.c#L52)  and [61](https://github.com/FemtoEmacs/Femto-Emacs/blob/master/utils.c#L6) we are using the function `isspace (3)` in a loop which is correct at certain degree, it actually does what is supposed to do, but if we think for a moment we can assert that it is not ok, we don't know if the function `isspace (3)` was _inlined_ in the **libc** the user is using, if the this function was not _inlined_ in the library being used then upon execution of [FemtoEmacs](https://github.com/FemtoEmacs/Femto-Emacs) addresses will pushed and poped to the stack, and program will jump reppeatedly to those addresses, which has its costs...

The correct approach would be something like this:

``` C
  while (*ptr == ' ' || *ptr == '\n' || *ptr == '\r'  || *ptr == '\t')
          ++ptr;
```

and

``` C
  while (*ptr == ' ' || *ptr == '\n' || *ptr == '\r'  || *ptr == '\t')
          --ptr;
```

I know that `isspace (c)` is more readdble than `*ptr == ' ' || *ptr == '\n' || *ptr == '\r'  || *ptr == '\t'` but we can make more readable by defining a macro that expands to that expression, for instance:

``` C
  #define IS_SPACE(chr) (chr == ' ' || chr == '\n' || chr == '\r'  || chr == '\t')
```

and change those lines to:

``` C
  while (IS_SPACE (*ptr))
          ++ptr;
```

and

``` C
  while (IS_SPACE (*ptr))
          --ptr;
```

In my first commit to this project I did just that, but I failed to mention why I did not used `isspace (3)`.

Anyway I hope you consider this.

Cheers.
-- Chi

**Comment by hughbarney** [comment]
Please do a pull request for this and I will grab.  However I may get rid of this function altogether at some point as femtolisp has a string.trim function that we can use in buffer men.

**Comment by chigoncalves** [comment]
Later in the day I'll try do it.
